#!/bin/bash
yum install -y aws-cli
cd /home/ec2-user/
sudo yum install ruby -y
aws s3 cp 's3://aws-codedeploy-us-east-1/latest/codedeploy-agent.noarch.rpm' . --region us-east-1
yum -y install codedeploy-agent.noarch.rpm
